name: Build And Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main"
        sudo apt update
        sudo apt install -y clang-18 libllvm18 llvm-18-dev cmake
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100

    - name: Cache CMake build and dependencies
      uses: actions/cache@v4
      with:
        path: |
          build
          build/_deps
          ~/.cache/cmake
        key: cmake-build-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/*.cmake') }}
        restore-keys: |
          cmake-build-${{ runner.os }}-

    - name: Configure CMake
      run: cmake -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=23

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: build/tests